/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.settings.ActionSettings;
import gui.settings.ButtonSettings;
import gui.settings.IRegulator;
import gui.settings.IconSettings;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class AccountScreen extends javax.swing.JFrame implements IRegulator{

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        AccountScreenPanel.setFocusable(true);
    }

    /**
     * Creates new form AccountScreen
     */
    public AccountScreen() {
        initComponents();
        getEdits();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountScreenPanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        UserNameSurnameLabel = new javax.swing.JLabel();
        EuroIcon = new javax.swing.JLabel();
        BalanceLabel = new javax.swing.JLabel();
        WithdrawIcon = new javax.swing.JLabel();
        WithdrawButton = new javax.swing.JButton();
        DepositIcon = new javax.swing.JLabel();
        DepositButton = new javax.swing.JButton();
        TransferIcon = new javax.swing.JLabel();
        PaymentsButton = new javax.swing.JButton();
        TransferButton = new javax.swing.JButton();
        PaymentsIcon = new javax.swing.JLabel();
        LogoutIcon = new javax.swing.JLabel();
        SettingIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Screen");

        AccountScreenPanel.setBackground(new java.awt.Color(204, 204, 204));
        AccountScreenPanel.setMaximumSize(new java.awt.Dimension(1500, 1500));
        AccountScreenPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(51, 51, 255));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("WELCOME!");
        AccountScreenPanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 63, 200, 50));

        UserNameSurnameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 32)); // NOI18N
        UserNameSurnameLabel.setForeground(new java.awt.Color(51, 51, 255));
        UserNameSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNameSurnameLabel.setText("[USER NAME AND SURNAME]");
        AccountScreenPanel.add(UserNameSurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 131, 531, 50));

        EuroIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/euroIcon.png"))); // NOI18N
        AccountScreenPanel.add(EuroIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 217, -1, 143));

        BalanceLabel.setFont(new java.awt.Font("Serif", 1, 54)); // NOI18N
        BalanceLabel.setText("Balance");
        AccountScreenPanel.add(BalanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 263, 250, 50));

        WithdrawIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/withdrawIcon.png"))); // NOI18N
        AccountScreenPanel.add(WithdrawIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 431, -1, -1));

        WithdrawButton.setBackground(new java.awt.Color(255, 204, 204));
        WithdrawButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        WithdrawButton.setText("Withdraw");
        WithdrawButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WithdrawButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WithdrawButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WithdrawButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WithdrawButtonMouseExited(evt);
            }
        });
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });
        AccountScreenPanel.add(WithdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 568, 110, 41));

        DepositIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/depositIcon.png"))); // NOI18N
        AccountScreenPanel.add(DepositIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 431, -1, -1));

        DepositButton.setBackground(new java.awt.Color(153, 255, 153));
        DepositButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        DepositButton.setText("Deposit");
        DepositButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DepositButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DepositButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DepositButtonMouseExited(evt);
            }
        });
        DepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositButtonActionPerformed(evt);
            }
        });
        AccountScreenPanel.add(DepositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 568, 110, 41));

        TransferIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/transferIcon.png"))); // NOI18N
        AccountScreenPanel.add(TransferIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 431, -1, -1));

        PaymentsButton.setBackground(new java.awt.Color(102, 255, 204));
        PaymentsButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        PaymentsButton.setText("Payments");
        PaymentsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PaymentsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PaymentsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PaymentsButtonMouseExited(evt);
            }
        });
        PaymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentsButtonActionPerformed(evt);
            }
        });
        AccountScreenPanel.add(PaymentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 568, 110, 41));

        TransferButton.setBackground(new java.awt.Color(255, 255, 51));
        TransferButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        TransferButton.setText("Transfer");
        TransferButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TransferButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransferButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransferButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransferButtonMouseExited(evt);
            }
        });
        TransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferButtonActionPerformed(evt);
            }
        });
        AccountScreenPanel.add(TransferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 568, 110, 41));

        PaymentsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/paymentsIcon.png"))); // NOI18N
        AccountScreenPanel.add(PaymentsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 431, -1, -1));

        LogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/logoutIcon.png"))); // NOI18N
        LogoutIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutIconMouseClicked(evt);
            }
        });
        AccountScreenPanel.add(LogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 33, -1, -1));

        SettingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/settingsIcon.png"))); // NOI18N
        SettingIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SettingIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingIconMouseClicked(evt);
            }
        });
        AccountScreenPanel.add(SettingIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountScreenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountScreenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Button Coloring and Icon Changing
    
     private void setBgFg(Component c)
    {
        ButtonSettings.setBgFg((JButton) c, Color.BLACK, Color.WHITE);
    }
    
    private void WithdrawButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawButtonMouseClicked
        
    }//GEN-LAST:event_WithdrawButtonMouseClicked

    private void WithdrawButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawButtonMouseEntered
        this.setBgFg(evt.getComponent());
      //  IconSettings.changeIcon(WithdrawIcon,"withdrawIcon2.png");
    }//GEN-LAST:event_WithdrawButtonMouseEntered

    private void WithdrawButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_WithdrawButtonMouseExited

    private void DepositButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositButtonMouseClicked
        
    }//GEN-LAST:event_DepositButtonMouseClicked

    private void DepositButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositButtonMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_DepositButtonMouseEntered

    private void DepositButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_DepositButtonMouseExited

    private void TransferButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferButtonMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_TransferButtonMouseEntered

    private void TransferButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_TransferButtonMouseExited

    private void TransferButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferButtonMouseClicked
        
    }//GEN-LAST:event_TransferButtonMouseClicked

    private void PaymentsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentsButtonMouseClicked
        
    }//GEN-LAST:event_PaymentsButtonMouseClicked

    private void PaymentsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentsButtonMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_PaymentsButtonMouseEntered

    private void PaymentsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentsButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_PaymentsButtonMouseExited

    
    /**
     * Actions for Buttons
     * @param evt 
     */
    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawButtonActionPerformed
        ActionSettings.setVisible(this, new WithDrawScreen());
    }//GEN-LAST:event_WithdrawButtonActionPerformed

    private void DepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositButtonActionPerformed
        ActionSettings.setVisible(this, new DepositScreen());
    }//GEN-LAST:event_DepositButtonActionPerformed

    private void TransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferButtonActionPerformed
        ActionSettings.setVisible(this, new TransferScreen());
    }//GEN-LAST:event_TransferButtonActionPerformed

    private void PaymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentsButtonActionPerformed
        ActionSettings.setVisible(this, new PaymentsScreen());
    }//GEN-LAST:event_PaymentsButtonActionPerformed

    private void LogoutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutIconMouseClicked
        ActionSettings.setVisible(this, new LoginScreen());
    }//GEN-LAST:event_LogoutIconMouseClicked

    private void SettingIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingIconMouseClicked
        ActionSettings.setVisible(this, new SettingScreen());
    }//GEN-LAST:event_SettingIconMouseClicked

   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountScreenPanel;
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JButton DepositButton;
    private javax.swing.JLabel DepositIcon;
    private javax.swing.JLabel EuroIcon;
    private javax.swing.JLabel LogoutIcon;
    private javax.swing.JButton PaymentsButton;
    private javax.swing.JLabel PaymentsIcon;
    private javax.swing.JLabel SettingIcon;
    private javax.swing.JButton TransferButton;
    private javax.swing.JLabel TransferIcon;
    private javax.swing.JLabel UserNameSurnameLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JButton WithdrawButton;
    private javax.swing.JLabel WithdrawIcon;
    // End of variables declaration//GEN-END:variables
}
